name: Manual Build Nesbox

on:
  workflow_dispatch: # 允许你手动点击运行
  push:
    branches: [ main, master ] # 提交代码时也会自动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      # 将编译好的静态文件打包并上传到 GitHub Actions 页面
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nesbox-web-dist # 下载时的文件名
          path: packages/webapp/dist/ # 编译结果所在的目录
